// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkhvRb1p7VsTOogGJSb1X2fRDX8g0HEI',
    appId: '1:243209972551:web:cfafef00cab3c47fdfba62',
    messagingSenderId: '243209972551',
    projectId: 'apihpfirebase',
    authDomain: 'apihpfirebase.firebaseapp.com',
    databaseURL: 'https://apihpfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'apihpfirebase.appspot.com',
    measurementId: 'G-9HGDDY65YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6wpqH5SOyB-AokJrNKT_DE6M2K_t9oY',
    appId: '1:243209972551:android:b63bb8fba1fad85cdfba62',
    messagingSenderId: '243209972551',
    projectId: 'apihpfirebase',
    databaseURL: 'https://apihpfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'apihpfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHHx4Qb6WzNeKbgXAG0gQ8KGrfO92dxb8',
    appId: '1:243209972551:ios:2d7f16b3ad067a6ddfba62',
    messagingSenderId: '243209972551',
    projectId: 'apihpfirebase',
    databaseURL: 'https://apihpfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'apihpfirebase.appspot.com',
    iosBundleId: 'com.example.projekUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHHx4Qb6WzNeKbgXAG0gQ8KGrfO92dxb8',
    appId: '1:243209972551:ios:b12f55b98535073adfba62',
    messagingSenderId: '243209972551',
    projectId: 'apihpfirebase',
    databaseURL: 'https://apihpfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'apihpfirebase.appspot.com',
    iosBundleId: 'com.example.projekUts.RunnerTests',
  );
}
